export const mockDataService = {
  getActiveJobs: () => [
    {
      id: 'mock-1',
      title: 'Senior React Developer',
      description: 'We are looking for an experienced React developer to join our team. You will work on cutting-edge projects and collaborate with a talented team of developers.',
      location: 'Ho Chi Minh City',
      salaryRange: '1500 - 3000 USD',
      experience: '3+ years',
      deadline: '2024-12-31T23:59:59.000Z',
      createdAt: '2024-06-20T10:00:00Z',
      category: 'Công nghệ thông tin',
      type: 'Full-time',
      position: 'Frontend Developer',
      skills: ['JavaScript', 'React', 'TypeScript', 'Node.js'],
      companyName: 'Tech Company',
      companyLogo: null,
      status: 'active',
      isExpired: false,
      daysUntilDeadline: 41,
      isRecent: true,
      displaySalary: '$1,500 - $3,000',
      displayLocation: 'Ho Chi Minh City',
      displayExperience: '3+ years',
      displayCategory: 'Công nghệ thông tin',
      displayType: 'Full-time',
      displayPosition: 'Frontend Developer',
      skillsDisplay: 'JavaScript, React, TypeScript, Node.js'
    },
    {
      id: 'mock-2',
      title: 'UI/UX Designer',
      description: 'Creative designer needed for web and mobile applications. Join our design team and help create amazing user experiences.',
      location: 'Remote',
      salaryRange: '1000 - 2000 USD',
      experience: '2+ years',
      deadline: '2024-12-25T23:59:59.000Z',
      createdAt: '2024-06-18T14:30:00Z',
      category: 'Thiết kế',
      type: 'Part-time',
      position: 'UI/UX Designer',
      skills: ['Figma', 'Adobe XD', 'Sketch', 'Photoshop'],
      companyName: 'Design Studio',
      companyLogo: null,
      status: 'active',
      isExpired: false,
      daysUntilDeadline: 35,
      isRecent: true,
      displaySalary: '$1,000 - $2,000',
      displayLocation: 'Remote',
      displayExperience: '2+ years',
      displayCategory: 'Thiết kế',
      displayType: 'Part-time',
      displayPosition: 'UI/UX Designer',
      skillsDisplay: 'Figma, Adobe XD, Sketch, Photoshop'
    },
    {
      id: 'mock-3',
      title: 'Backend Developer (Node.js)',
      description: 'Join our backend team to build scalable APIs and microservices. Experience with Node.js and databases required.',
      location: 'Da Nang',
      salaryRange: '1200 - 2500 USD',
      experience: '2-5 years',
      deadline: '2025-01-15T23:59:59.000Z',
      createdAt: '2024-06-15T09:00:00Z',
      category: 'Công nghệ thông tin',
      type: 'Full-time',
      position: 'Backend Developer',
      skills: ['JavaScript', 'Node.js', 'MySQL', 'MongoDB', 'Redis'],
      companyName: 'Startup Inc',
      companyLogo: null,
      status: 'active',
      isExpired: false,
      daysUntilDeadline: 56,
      isRecent: false,
      displaySalary: '$1,200 - $2,500',
      displayLocation: 'Da Nang',
      displayExperience: '2-5 years',
      displayCategory: 'Công nghệ thông tin',
      displayType: 'Full-time',
      displayPosition: 'Backend Developer',
      skillsDisplay: 'JavaScript, Node.js, MySQL, MongoDB, Redis'
    },
    {
      id: 'mock-4',
      title: 'DevOps Engineer',
      description: 'Experienced DevOps engineer to manage our cloud infrastructure and CI/CD pipelines.',
      location: 'Hanoi',
      salaryRange: '2000 - 4000 USD',
      experience: '3-7 years',
      deadline: '2024-12-20T23:59:59.000Z',
      createdAt: '2024-06-10T08:00:00Z',
      category: 'Công nghệ thông tin',
      type: 'Full-time',
      position: 'DevOps Engineer',
      skills: ['AWS', 'Docker', 'Kubernetes', 'Jenkins', 'Terraform'],
      companyName: 'Cloud Solutions',
      companyLogo: null,
      status: 'active',
      isExpired: false,
      daysUntilDeadline: 30,
      isRecent: false,
      displaySalary: '$2,000 - $4,000',
      displayLocation: 'Hanoi',
      displayExperience: '3-7 years',
      displayCategory: 'Công nghệ thông tin',
      displayType: 'Full-time',
      displayPosition: 'DevOps Engineer',
      skillsDisplay: 'AWS, Docker, Kubernetes, Jenkins, Terraform'
    },
    {
      id: 'mock-5',
      title: 'Product Manager',
      description: 'Strategic product manager to lead our product development initiatives and work with cross-functional teams.',
      location: 'Ho Chi Minh City',
      salaryRange: '1800 - 3500 USD',
      experience: '4+ years',
      deadline: '2025-01-10T23:59:59.000Z',
      createdAt: '2024-06-05T16:45:00Z',
      category: 'Quản lý sản phẩm',
      type: 'Full-time',
      position: 'Product Manager',
      skills: ['Product Strategy', 'Agile', 'Analytics', 'Leadership'],
      companyName: 'Product Co',
      companyLogo: null,
      status: 'active',
      isExpired: false,
      daysUntilDeadline: 51,
      isRecent: false,
      displaySalary: '$1,800 - $3,500',
      displayLocation: 'Ho Chi Minh City',
      displayExperience: '4+ years',
      displayCategory: 'Quản lý sản phẩm',
      displayType: 'Full-time',
      displayPosition: 'Product Manager',
      skillsDisplay: 'Product Strategy, Agile, Analytics, Leadership'
    }
  ],

  getDraftJobs: () => [
    {
      id: 'draft-1',
      title: 'Senior Java Developer - Draft',
      description: 'Draft job posting for Java developer position.',
      location: 'Ho Chi Minh City',
      salaryRange: '2000 - 3500 USD',
      experience: '5+ years',
      deadline: '2025-02-01T23:59:59.000Z',
      createdAt: '2024-06-21T10:00:00Z',
      category: 'Công nghệ thông tin',
      type: 'Full-time',
      position: 'Backend Developer',
      skills: ['Java', 'Spring Boot', 'MySQL', 'REST API'],
      companyName: 'Enterprise Corp',
      companyLogo: null,
      status: 'draft',
      isExpired: false,
      daysUntilDeadline: 62,
      isRecent: true,
      displaySalary: '$2,000 - $3,500',
      displayLocation: 'Ho Chi Minh City',
      displayExperience: '5+ years',
      displayCategory: 'Công nghệ thông tin',
      displayType: 'Full-time',
      displayPosition: 'Backend Developer',
      skillsDisplay: 'Java, Spring Boot, MySQL, REST API'
    }
  ],

  getApplicationsCount: (jobId) => {
    const counts = {
      'mock-1': 23,
      'mock-2': 15,
      'mock-3': 8,
      'mock-4': 31,
      'mock-5': 12,
      'draft-1': 0
    };
    return counts[jobId] || Math.floor(Math.random() * 25) + 1;
  },

  getJobApplications(jobId) {
    const applications = [
      {
        id: 'app_1',
        applicationId: 'mock_app_001',
        jobId: jobId,
        userId: 'user_1',
        userFullname: 'Nguyễn Văn An',
        userEmail: 'nguyenvanan@email.com',
        userPhone: '0901234567',
        status: 'pending',
        appliedAt: '2024-01-15T10:30:00Z',
        resumeFile: ['Nguyen_Van_An_CV.pdf'],
        resumeId: 'resume_1',
        coverLetter: 'Tôi rất quan tâm đến vị trí này và tin rằng kinh nghiệm của tôi phù hợp với yêu cầu công việc.',
        canUpdate: true
      },
      {
        id: 'app_2',
        applicationId: 'mock_app_002',
        jobId: jobId,
        userId: 'user_2',
        userFullname: 'Trần Thị Bình',
        userEmail: 'tranthibinh@email.com',
        userPhone: '0902345678',
        status: 'accepted',
        appliedAt: '2024-01-14T14:20:00Z',
        resumeFile: ['Tran_Thi_Binh_Resume.pdf'],
        resumeId: 'resume_2',
        coverLetter: 'Với 3 năm kinh nghiệm trong lĩnh vực này, tôi tin tưởng có thể đóng góp tích cực cho công ty.',
        canUpdate: true
      },
      {
        id: 'app_3',
        applicationId: 'mock_app_003',
        jobId: jobId,
        userId: 'user_3',
        userFullname: 'Lê Văn Cường',
        userEmail: 'levancuong@email.com',
        userPhone: '0903456789',
        status: 'rejected',
        appliedAt: '2024-01-13T09:15:00Z',
        resumeFile: ['Le_Van_Cuong_CV.pdf'],
        resumeId: 'resume_3',
        coverLetter: null,
        canUpdate: true
      },
      {
        id: 'app_4',
        applicationId: 'mock_app_004',
        jobId: jobId,
        userId: 'user_4',
        userFullname: 'Phạm Thị Dung',
        userEmail: 'phamthidung@email.com',
        userPhone: '0904567890',
        status: 'reviewing',
        appliedAt: '2024-01-12T16:45:00Z',
        resumeFile: ['Pham_Thi_Dung_Resume.pdf'],
        resumeId: 'resume_4',
        coverLetter: 'Tôi rất hứng thú với cơ hội làm việc tại công ty và mong muốn được thể hiện khả năng của mình.',
        canUpdate: true
      },
      {
        id: 'app_5',
        applicationId: 'mock_app_005',
        jobId: jobId,
        userId: 'user_5',
        userFullname: 'Hoàng Văn Em',
        userEmail: 'hoangvanem@email.com',
        userPhone: '0905678901',
        status: 'interviewed',
        appliedAt: '2024-01-11T11:30:00Z',
        resumeFile: ['Hoang_Van_Em_CV.pdf'],
        resumeId: 'resume_5',
        coverLetter: 'Với background về công nghệ và passion cho innovation, tôi tin mình sẽ là ứng viên phù hợp.',
        canUpdate: true
      }
    ];

    return applications.map(app => ({
      ...app,
      jobTitle: this.mockJobs.find(job => job.id === jobId)?.title || 'Unknown Job'
    }));
  }
};